name: Continous Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'JohanLopes'
          reponame: 'johanlopes.fr'
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
          useyarn: true
          cname: 'johanlopes.fr'
